name: 'Qiniu Upload'
description: 'github action for uploading files to qiniu'
author: 'zhangwweijie'

# 在此添加您的操作品牌。这将出现在 GitHub Marketplace 上。
branding:
  icon: 'heart'
  color: 'red'

# 定义相关变量  
inputs:
  milliseconds:
    description: '测试'
    required: true
    default: '1000'
  access_key:
    description: 'access key'
    required: true
  secret_key:
    description: 'secret key'
    required: true
  bucket:
    description: 'bucket'
    required: true
  zone:
    description: 'zone'
    default: 'Zone_z1'
    required: false
  source_dir:
    description: '上传的文件路径'
    default: './dist'
    required: false
  dest_dir:
    description: 'dest dir, namely key prefix'
    default: '/'
    required: false
  ignore_source_map:
    description: 'ignore source maps'
    default: true
    required: false

# Define your outputs here.
outputs:
  time:
    description: '111Your output description here'
    
runs:
  using: 'node20'
  main: 'lib/index.js'
