name: 'Qiniu Upload'
description: 'github action for uploading files to qiniu'
author: 'zhangwweijie'

# 在此添加您的操作品牌。这将出现在 GitHub Marketplace 上。
branding:
  icon: 'heart'
  color: 'red'
# 定义相关变量  
inputs:
  access_key:
    description: 'access key'
    required: true
  secret_key:
    description: 'secret key'
    required: true
  bucket:
    description: 'bucket'
    required: true
  is_cover:
    description: '是否覆盖上传'
    default:  false
    required: false
  source_dir:
    description: '上传的文件路径'
    default: './dist'
    required: false
  dest_dir:
    description: 'dest dir, namely key prefix'
    default: '/'
    required: false
  ignore_source_map:
    description: 'ignore source maps'
    default: true
    required: false
    
runs:
  using: 'node20'
  main: 'dist/index.js'
