name: 持续集成

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-upload:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - name: Install Dependencies
        id: pnpm-install
        run: pnpm install

      - name: 构建
        id: pnpm-build
        run: pnpm run all

      - name: 本地测试Action文件上传
        id: test-action
        uses: ./
        with:
          # Your qiniu access key, required.
          access_key: ${{ secrets.QINIU_ACCESS_KEY }}

          # Your qiniu secret key, required.
          secret_key: ${{ secrets.QINIU_SECRET_KEY }}

          # Bucket name, required.
          bucket: ${{ secrets.QINIU_BUCKET }}

          is_cover : true

          source_dir: './dist'

          dest_dir: ''



